# Generated by Django 5.0.3 on 2024-03-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pupils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('grade1', models.IntegerField()),
                ('grade2', models.IntegerField()),
                ('grade3', models.IntegerField()),
            ],
        ),
    ]
